<?php
function ggw_profile_edit_init() {
	//Customize Profile
	if(arg(0) == 'user' && arg(1) == 'register') {
		drupal_add_css(drupal_get_path('module', 'ggw_profile_edit').'/css/field_hide.css');
	} else if(arg(0) == 'admin' && arg(1) == 'user' && arg(2) == 'user' && arg(3) == 'create') {
		drupal_add_js(drupal_get_path('module', 'ggw_profile_edit').'/js/conditional_fieldsets.js');
	}
}

function ggw_profile_edit_form_user_profile_form_alter(&$form, &$form_state) {
	unset ($form['contact']);
}

function ggw_profile_edit_menu() {
  $items['pos-api/customer/add-customer'] = array(
    'title' => 'Add customer',
    'description' => 'Populate inventory for an item.',
    'page callback' => 'ggw_profile_add_new_user_ins',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK
  );

  return $items;
}

function ggw_profile_add_new_user_ins() {
	$failed_response = array(
		'status' => false,
		'error' => 'Employee token has expired.'
	);

	$request = json_decode($_POST['request']);
	$uid = _pos_api_expose_uid_from_token($request->token);

	$companyName = trim($request->companyName);
	$firstName = trim($request->firstName);
    $lastName = trim($request->lastName);
    $accountId = trim($request->accountId);
    $phone = trim($request->phone);
    $email = trim($request->email);
    $password = trim($request->password);
    $taxId = trim($request->taxId);
    $tobacco = trim($request->tobacco);
    $tremarks = trim($request->tremarks);
    $tdate = trim($request->tdate);
    $st_one = trim($request->st_one);
    $st_two = trim($request->st_two);
    $city = trim($request->city);
    $state = trim($request->state);
    $zip = trim($request->zip);
    $fax = trim($request->fax);

	if($uid) {
		$userCount = db_result(db_query("SELECT COUNT(*) FROM users WHERE name = '%s'", $accountId));
		if($userCount == 0) {
			pos_api_expose_respond(array(
				'status' => true,
				'error' => 'Customer account found.'
			));

			/*if($password) {
				$password = md5($password);
			} else {
				$password = md5($accountId);
			}

			if(empty($email)) {
				$email =  $accountId."@general-goods.com";
			}

			$sql = "INSERT INTO users (name, pass, mail, mode, sort, threshold, signature_format, created, access, login, status, timezone, data, timezone_name) VALUES('".$accountId."', '".$password."', '".$email."', '0', '0', '0', '0', '".time()."', '".time()."', '".time()."', '1', '-2600', NULL, 'America/Chicago');";
			db_query($sql);
			$uid_created = db_last_insert_id('users', 'uid');
			$query = "INSERT INTO users_roles (uid, rid) VALUES('".$uid_created."', '9');";
			db_query($query);*/
		} else {
			pos_api_expose_respond(array(
				'status' => false,
				'error' => 'Customer account number already exists.'
			));
		}
	} else {
		pos_api_expose_respond($failed_response);
	}
}

function ggw_profile_edit_form_alter(&$form, $form_state, $form_id) {
	if($form_id == 'user_register' && arg(0) == 'admin' && arg(1) == 'pos-api' && arg(2) == 'add-customer') {
		foreach($form['account']['roles']['#options'] as $key => $val) {
			if(strpos(strtolower($val), 'customer') === FALSE) {
				unset($form['account']['roles']['#options'][$key]);
			}
		}
	}
}