<?php
function ggw_profile_edit_init() {
	//Customize Profile
	if(arg(0) == 'user' && arg(1) == 'register') {
		drupal_add_css(drupal_get_path('module', 'ggw_profile_edit').'/css/field_hide.css');
	} else if(arg(0) == 'admin' && arg(1) == 'user' && arg(2) == 'user' && arg(3) == 'create') {
		drupal_add_js(drupal_get_path('module', 'ggw_profile_edit').'/js/conditional_fieldsets.js');
	}
}

function ggw_profile_edit_form_user_profile_form_alter(&$form, &$form_state) {
	unset ($form['contact']);
}

function ggw_profile_edit_menu() {
  $items['pos-api/customer/add-customer'] = array(
    'title' => 'Add customer',
    'description' => 'Populate inventory for an item.',
    'page callback' => 'ggw_profile_add_new_user_ins',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
    'file' => 'includes/user_registration_callbacks.inc'
  );

  return $items;
}

function ggw_profile_edit_form_alter(&$form, $form_state, $form_id) {
	if($form_id == 'user_register' && arg(0) == 'admin' && arg(1) == 'pos-api' && arg(2) == 'add-customer') {
		foreach($form['account']['roles']['#options'] as $key => $val) {
			if(strpos(strtolower($val), 'customer') === FALSE) {
				unset($form['account']['roles']['#options'][$key]);
			}
		}
	}
}