<?php
function ggw_profile_edit_init() {
	//Customize Profile
	if(arg(0) == 'user' && arg(1) == 'register') {
		drupal_add_css(drupal_get_path('module', 'ggw_profile_edit').'/css/field_hide.css');
	} else if(arg(0) == 'admin' && arg(1) == 'user' && arg(2) == 'user' && arg(3) == 'create') {
		drupal_add_js(drupal_get_path('module', 'ggw_profile_edit').'/js/conditional_fieldsets.js');
	}
}

function ggw_profile_edit_form_user_profile_form_alter(&$form, &$form_state) {
	unset ($form['contact']);
}

function ggw_profile_edit_menu() {
  $items['admin/pos-api/add-customer'] = array(
    'title' => 'Add customer',
    'description' => 'Populate inventory for an item.',
    'page callback' => 'ggw_profile_add_new_user',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK
  );

  return $items;
}

function ggw_profile_add_new_user() {
	//$token = $_GET['token'];
	//$uid = _pos_api_expose_uid_from_token($token);
	//if($uid) {
	//} else {
	//	print "Access denied to invoice.";
	//}
	drupal_add_js(drupal_get_path('module', 'ggw_profile_edit').'/js/conditional_fieldsets.js');
	drupal_add_js(drupal_get_path('module', 'ggw_profile_edit').'/js/pos_signup_form.js');
	drupal_add_css(drupal_get_path('module', 'ggw_profile_edit').'/css/embedded_signup.css');
	return drupal_get_form('user_register');
}

function ggw_profile_edit_form_alter(&$form, $form_state, $form_id) {
	if($form_id == 'user_register' && arg(0) == 'admin' && arg(1) == 'pos-api' && arg(2) == 'add-customer') {
		foreach($form['account']['roles']['#options'] as $key => $val) {
			if(strpos(strtolower($val), 'customer') === FALSE) {
				unset($form['account']['roles']['#options'][$key]);
			}
		}
	}
}