<?php
function pos_bulk_desc_menu() {
	$items['admin/settings/bulk-descriptions'] = array(
		'type' => MENU_NROMAL_ITEM,
		'title' => 'Bulk Description Editing',
		'description' => 'Bulk presistent description editor.',
		'page callback' => 'pos_bulk_desc_config',
		'access arguments' => array('administer site configuration')
	);

	return $items;
}

function pos_bulk_desc_config() {
	return drupal_get_form('pos_bulk_desc_config_form');
}

function pos_bulk_desc_config_form() {
	$form = array();

	$form['database'] = array(
		'#type' => 'fieldset',
		'#title' => 'Database Information',
		'#description' => 'Database host to store presistent descriptions',
		'#collapsible' => false
	);

	$form['database']['host'] = array(
		'#title' => 'Database Host',
		'#type' => 'textfield',
		'#required' => true,
		'#default_value' => variable_get('pos_bulk_db_host', '')
	);

	$form['database']['username'] = array(
		'#title' => 'Database Username',
		'#type' => 'textfield',
		'#required' => true,
		'#default_value' => variable_get('pos_bulk_db_username', '')
	);
	
	$form['database']['password'] = array(
		'#title' => 'Database Password',
		'#type' => 'textfield',
		'#required' => true,
		'#default_value' => variable_get('pos_bulk_db_password', '')
	);
	
	$form['database']['dbname'] = array(
		'#title' => 'Database Name',
		'#type' => 'textfield',
		'#required' => true,
		'#default_value' => variable_get('pos_bulk_db_dbname', '')
	);
	

	$form['submit'] = array(
		'#type' => 'submit',
		'#value' => 'Save'
	);

	return $form;
}

function pos_bulk_desc_config_form_validate($form, &$form_state) {
	$link = pos_bulk_desc_get_link($form_state['values']['host'], $form_state['values']['username'], $form_state['values']['password'], $form_state['values']['dbname']);

	if($link) {
		variable_set('pos_bulk_desc_db', true);
	} else {
		variable_set('pos_bulk_desc_db', false);
		form_set_error('host', 'The database credentials you provided are invalid.');
	}
}

function pos_bulk_desc_get_saved_link() {
	return pos_bulk_desc_get_link(variable_get('pos_bulk_db_host', ''), variable_get('pos_bulk_db_username', ''), variable_get('pos_bulk_db_password', ''), variable_get('pos_bulk_db_dbname', ''));
}

function pos_bulk_desc_get_link($host, $username, $password, $db) {
	static $link = NULL;

	if(is_null($link)) {
		if(!empty($host)) {
			$link = mysqli_connect($host, $username, $password, $db);
		} else {
			$link = false;
		}
	}
	
	return $link;
}

function pos_bulk_desc_config_form_submit($form, &$form_state) {
	variable_set('pos_bulk_db_host', $form_state['values']['host']);
	variable_set('pos_bulk_db_username', $form_state['values']['username']);
	variable_set('pos_bulk_db_password', $form_state['values']['password']);
	variable_set('pos_bulk_db_dbname', $form_state['values']['dbname']);
}

function pos_bulk_desc_nodeapi(&$node, $op, $a3 = NULL, $a4 = NULL) {
	if($node->type == 'product') {
		//dpm($node);
		if($op == "presave") {
			$link = pos_bulk_desc_get_saved_link();
			if($link) {
				if(!empty($node->title)) {
				$link->query("INSERT INTO node_desc_syncs (nid, title, model, modified) VALUES ('".$link->escape_string($node->nid)."',  '".$link->escape_string(html_entity_decode($node->title))."',  '".$link->escape_string($node->model)."', '".time()."');");
				}
				pos_bulk_desc_node_save_data($node, $link);
			}
		} else if($op == "load") {
			$link = pos_bulk_desc_get_saved_link();
			
			if($link) {
				$result = $link->query("SELECT title FROM node_desc_syncs WHERE model = '".$node->model."' ORDER BY modified DESC");
				$row = mysqli_fetch_array($result);
				if(!empty($row['title'])) {
					$node->title = $row['title'];
				}
				pos_build_desc_node_load_data($node, $link);
			}
		}
	}
}

function pos_bulk_desc_node_save_data($node, $link) {
	$data = array();

	foreach($node as $node_field_key => $node_field_value) {
		if(strpos($node_field_key, 'field_prod') !== FALSE) {
			$data[$node_field_key] = $node_field_value[0]['value'];
		}
	}
	
	if(!empty($data)) {
		$data = serialize($data);
		$link->query("INSERT INTO node_cck_syncs (nid, data, model, modified) VALUES ('".$link->escape_string($node->nid)."',  '".$link->escape_string($data)."',  '".$link->escape_string($node->model)."', '".time()."');");
	}
}

function pos_build_desc_node_load_data(&$node, $link) {
	$result = $link->query("SELECT data FROM node_cck_syncs WHERE model = '".$link->escape_string($node->model)."' ORDER BY modified DESC");
	$row = mysqli_fetch_array($result);
	if(!empty($row['data'])) {
		$data = unserialize($row['data']);
		foreach($data as $node_field_key => $node_field_value) {
			$field = $node->$node_field_key;
			$field[0]['value'] = $node_field_value;
			$node->$node_field_key = $field;
			//$node->$node_field_key[0]['value'] = $node_field_value;
		}
	}
}

function pos_bulk_desc_user($op, $edit, &$account, $category = NULL) {
	if($op == 'submit') {
		$link = pos_bulk_desc_get_saved_link();
		//dpm($edit);
		$link->query("REPLACE INTO user_pass_syncs (name, pass) VALUES ('".$account->name."', '".md5($edit['pass'])."')");
	}
}
/*
function pos_bulk_desc_views_data_alter(&$data) {
	//dpm($data);
}
*/
